// Code generated by counterfeiter. DO NOT EDIT.
package datafakes

import (
	"chat/pkg/data"
	"chat/pkg/rest/models"
	"context"
	"sync"
)

type FakeDBClientInterface struct {
	AddNewUserStub        func(context.Context, *models.User) error
	addNewUserMutex       sync.RWMutex
	addNewUserArgsForCall []struct {
		arg1 context.Context
		arg2 *models.User
	}
	addNewUserReturns struct {
		result1 error
	}
	addNewUserReturnsOnCall map[int]struct {
		result1 error
	}
	GetChatroomsByUserIdStub        func(context.Context, int32) ([]*models.UserChatroom, error)
	getChatroomsByUserIdMutex       sync.RWMutex
	getChatroomsByUserIdArgsForCall []struct {
		arg1 context.Context
		arg2 int32
	}
	getChatroomsByUserIdReturns struct {
		result1 []*models.UserChatroom
		result2 error
	}
	getChatroomsByUserIdReturnsOnCall map[int]struct {
		result1 []*models.UserChatroom
		result2 error
	}
	GetUserByUsernameStub        func(context.Context, string) (*models.User, error)
	getUserByUsernameMutex       sync.RWMutex
	getUserByUsernameArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getUserByUsernameReturns struct {
		result1 *models.User
		result2 error
	}
	getUserByUsernameReturnsOnCall map[int]struct {
		result1 *models.User
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDBClientInterface) AddNewUser(arg1 context.Context, arg2 *models.User) error {
	fake.addNewUserMutex.Lock()
	ret, specificReturn := fake.addNewUserReturnsOnCall[len(fake.addNewUserArgsForCall)]
	fake.addNewUserArgsForCall = append(fake.addNewUserArgsForCall, struct {
		arg1 context.Context
		arg2 *models.User
	}{arg1, arg2})
	stub := fake.AddNewUserStub
	fakeReturns := fake.addNewUserReturns
	fake.recordInvocation("AddNewUser", []interface{}{arg1, arg2})
	fake.addNewUserMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDBClientInterface) AddNewUserCallCount() int {
	fake.addNewUserMutex.RLock()
	defer fake.addNewUserMutex.RUnlock()
	return len(fake.addNewUserArgsForCall)
}

func (fake *FakeDBClientInterface) AddNewUserCalls(stub func(context.Context, *models.User) error) {
	fake.addNewUserMutex.Lock()
	defer fake.addNewUserMutex.Unlock()
	fake.AddNewUserStub = stub
}

func (fake *FakeDBClientInterface) AddNewUserArgsForCall(i int) (context.Context, *models.User) {
	fake.addNewUserMutex.RLock()
	defer fake.addNewUserMutex.RUnlock()
	argsForCall := fake.addNewUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDBClientInterface) AddNewUserReturns(result1 error) {
	fake.addNewUserMutex.Lock()
	defer fake.addNewUserMutex.Unlock()
	fake.AddNewUserStub = nil
	fake.addNewUserReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDBClientInterface) AddNewUserReturnsOnCall(i int, result1 error) {
	fake.addNewUserMutex.Lock()
	defer fake.addNewUserMutex.Unlock()
	fake.AddNewUserStub = nil
	if fake.addNewUserReturnsOnCall == nil {
		fake.addNewUserReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addNewUserReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDBClientInterface) GetChatroomsByUserId(arg1 context.Context, arg2 int32) ([]*models.UserChatroom, error) {
	fake.getChatroomsByUserIdMutex.Lock()
	ret, specificReturn := fake.getChatroomsByUserIdReturnsOnCall[len(fake.getChatroomsByUserIdArgsForCall)]
	fake.getChatroomsByUserIdArgsForCall = append(fake.getChatroomsByUserIdArgsForCall, struct {
		arg1 context.Context
		arg2 int32
	}{arg1, arg2})
	stub := fake.GetChatroomsByUserIdStub
	fakeReturns := fake.getChatroomsByUserIdReturns
	fake.recordInvocation("GetChatroomsByUserId", []interface{}{arg1, arg2})
	fake.getChatroomsByUserIdMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDBClientInterface) GetChatroomsByUserIdCallCount() int {
	fake.getChatroomsByUserIdMutex.RLock()
	defer fake.getChatroomsByUserIdMutex.RUnlock()
	return len(fake.getChatroomsByUserIdArgsForCall)
}

func (fake *FakeDBClientInterface) GetChatroomsByUserIdCalls(stub func(context.Context, int32) ([]*models.UserChatroom, error)) {
	fake.getChatroomsByUserIdMutex.Lock()
	defer fake.getChatroomsByUserIdMutex.Unlock()
	fake.GetChatroomsByUserIdStub = stub
}

func (fake *FakeDBClientInterface) GetChatroomsByUserIdArgsForCall(i int) (context.Context, int32) {
	fake.getChatroomsByUserIdMutex.RLock()
	defer fake.getChatroomsByUserIdMutex.RUnlock()
	argsForCall := fake.getChatroomsByUserIdArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDBClientInterface) GetChatroomsByUserIdReturns(result1 []*models.UserChatroom, result2 error) {
	fake.getChatroomsByUserIdMutex.Lock()
	defer fake.getChatroomsByUserIdMutex.Unlock()
	fake.GetChatroomsByUserIdStub = nil
	fake.getChatroomsByUserIdReturns = struct {
		result1 []*models.UserChatroom
		result2 error
	}{result1, result2}
}

func (fake *FakeDBClientInterface) GetChatroomsByUserIdReturnsOnCall(i int, result1 []*models.UserChatroom, result2 error) {
	fake.getChatroomsByUserIdMutex.Lock()
	defer fake.getChatroomsByUserIdMutex.Unlock()
	fake.GetChatroomsByUserIdStub = nil
	if fake.getChatroomsByUserIdReturnsOnCall == nil {
		fake.getChatroomsByUserIdReturnsOnCall = make(map[int]struct {
			result1 []*models.UserChatroom
			result2 error
		})
	}
	fake.getChatroomsByUserIdReturnsOnCall[i] = struct {
		result1 []*models.UserChatroom
		result2 error
	}{result1, result2}
}

func (fake *FakeDBClientInterface) GetUserByUsername(arg1 context.Context, arg2 string) (*models.User, error) {
	fake.getUserByUsernameMutex.Lock()
	ret, specificReturn := fake.getUserByUsernameReturnsOnCall[len(fake.getUserByUsernameArgsForCall)]
	fake.getUserByUsernameArgsForCall = append(fake.getUserByUsernameArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetUserByUsernameStub
	fakeReturns := fake.getUserByUsernameReturns
	fake.recordInvocation("GetUserByUsername", []interface{}{arg1, arg2})
	fake.getUserByUsernameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDBClientInterface) GetUserByUsernameCallCount() int {
	fake.getUserByUsernameMutex.RLock()
	defer fake.getUserByUsernameMutex.RUnlock()
	return len(fake.getUserByUsernameArgsForCall)
}

func (fake *FakeDBClientInterface) GetUserByUsernameCalls(stub func(context.Context, string) (*models.User, error)) {
	fake.getUserByUsernameMutex.Lock()
	defer fake.getUserByUsernameMutex.Unlock()
	fake.GetUserByUsernameStub = stub
}

func (fake *FakeDBClientInterface) GetUserByUsernameArgsForCall(i int) (context.Context, string) {
	fake.getUserByUsernameMutex.RLock()
	defer fake.getUserByUsernameMutex.RUnlock()
	argsForCall := fake.getUserByUsernameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDBClientInterface) GetUserByUsernameReturns(result1 *models.User, result2 error) {
	fake.getUserByUsernameMutex.Lock()
	defer fake.getUserByUsernameMutex.Unlock()
	fake.GetUserByUsernameStub = nil
	fake.getUserByUsernameReturns = struct {
		result1 *models.User
		result2 error
	}{result1, result2}
}

func (fake *FakeDBClientInterface) GetUserByUsernameReturnsOnCall(i int, result1 *models.User, result2 error) {
	fake.getUserByUsernameMutex.Lock()
	defer fake.getUserByUsernameMutex.Unlock()
	fake.GetUserByUsernameStub = nil
	if fake.getUserByUsernameReturnsOnCall == nil {
		fake.getUserByUsernameReturnsOnCall = make(map[int]struct {
			result1 *models.User
			result2 error
		})
	}
	fake.getUserByUsernameReturnsOnCall[i] = struct {
		result1 *models.User
		result2 error
	}{result1, result2}
}

func (fake *FakeDBClientInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addNewUserMutex.RLock()
	defer fake.addNewUserMutex.RUnlock()
	fake.getChatroomsByUserIdMutex.RLock()
	defer fake.getChatroomsByUserIdMutex.RUnlock()
	fake.getUserByUsernameMutex.RLock()
	defer fake.getUserByUsernameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDBClientInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ data.DBClientInterface = new(FakeDBClientInterface)
